import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/theme/app_theme.dart';
import '../../sleep/providers/sleep_provider.dart';
import '../../water/providers/water_provider.dart';
import '../../medications/providers/medication_provider.dart';

class AnalyticsScreen extends ConsumerStatefulWidget {
  const AnalyticsScreen({super.key});

  @override
  ConsumerState<AnalyticsScreen> createState() => _AnalyticsScreenState();
}

class _AnalyticsScreenState extends ConsumerState<AnalyticsScreen> {
  bool _isWeekly = true;
  int _activeTab = 0; // 0=All, 1=Sleep, 2=Water, 3=Medications

  static const _tabs = ['All', 'Sleep', 'Water', 'Medications'];

  @override
  void initState() {
    super.initState();
    Future.microtask(() {
      ref.read(sleepProvider.notifier).loadRecent();
      ref.read(waterProvider.notifier).loadToday();
      ref.read(medicationProvider.notifier).load();
    });
  }

  // ── Share report as text summary ─────────────────────────────────────────
  void _shareReport() {
    final sleep = ref.read(sleepProvider);
    final water = ref.read(waterProvider);
    final meds = ref.read(medicationProvider);
    final summary = '''
📊 SensiaHealth Weekly Report
━━━━━━━━━━━━━━━━━━━━━━━
🌙 Sleep: ${sleep.lastNightHours.toStringAsFixed(1)}h last night
   Avg this week: ${sleep.averageHours.toStringAsFixed(1)}h/night
💧 Hydration: ${(water.totalMl / 1000).toStringAsFixed(2)}L today
   Goal: ${(AppConstants.dailyWaterGoalMl / 1000).toStringAsFixed(1)}L
💊 Medications: ${meds.medications.where((m) => m.isTaken).length}/${meds.medications.length} taken today
━━━━━━━━━━━━━━━━━━━━━━━
Generated by SensiaHealth
''';

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('Report copied to clipboard!'),
        backgroundColor: AppColors.sage600,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
    Clipboard.setData(ClipboardData(text: summary));
  }

  // ── Export PDF (calls backend or shows pending state) ──────────────────
  void _exportPdf() {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('📄 Preparing your PDF report…'),
        backgroundColor: AppColors.plum700,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        action: SnackBarAction(
          label: 'OK',
          textColor: Colors.white,
          onPressed: () {},
        ),
      ),
    );
    // TODO: POST /reports/export?format=pdf and open the returned URL
  }

  void _exportCsv() {
    final sleep = ref.read(sleepProvider);
    final water = ref.read(waterProvider);
    final csv = [
      'Type,Value,Unit,Date',
      'Sleep,${sleep.lastNightHours.toStringAsFixed(1)},hours,${DateTime.now().toIso8601String().split("T").first}',
      'Water,${water.totalMl},ml,${DateTime.now().toIso8601String().split("T").first}',
    ].join('\n');
    Clipboard.setData(ClipboardData(text: csv));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text('📊 CSV data copied to clipboard'),
        backgroundColor: AppColors.plum700,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final sleep = ref.watch(sleepProvider);
    final water = ref.watch(waterProvider);
    final meds = ref.watch(medicationProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      body: Column(
        children: [
          // ── Header ─────────────────────────────────────────────────────
          Container(
            color: AppColors.card,
            child: SafeArea(
              bottom: false,
              child: Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.fromLTRB(20, 12, 20, 12),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            RichText(
                              text: TextSpan(
                                children: [
                                  TextSpan(
                                    text: 'Health ',
                                    style: GoogleFonts.playfairDisplay(
                                      fontSize: 24,
                                      fontWeight: FontWeight.w700,
                                      color: AppColors.plum900,
                                    ),
                                  ),
                                  TextSpan(
                                    text: 'Reports',
                                    style: GoogleFonts.playfairDisplay(
                                      fontSize: 24,
                                      fontWeight: FontWeight.w700,
                                      color: AppColors.rose500,
                                      fontStyle: FontStyle.italic,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text(
                              _isWeekly ? 'Last 7 days' : 'Last 30 days',
                              style: AppTextStyles.caption,
                            ),
                          ],
                        ),
                        GestureDetector(
                          onTap: () => setState(() => _isWeekly = !_isWeekly),
                          child: Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 12, vertical: 5),
                            decoration: BoxDecoration(
                              color: AppColors.plum50,
                              borderRadius: BorderRadius.circular(999),
                              border: Border.all(color: AppColors.plum200),
                            ),
                            child: Text(
                              _isWeekly ? 'Weekly ▾' : 'Monthly ▾',
                              style: const TextStyle(
                                fontSize: 11,
                                fontWeight: FontWeight.w700,
                                color: AppColors.plum700,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),

                  // Tab chips
                  SingleChildScrollView(
                    scrollDirection: Axis.horizontal,
                    padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
                    child: Row(
                      children: _tabs.asMap().entries.map((e) {
                        final i = e.key;
                        final t = e.value;
                        final isActive = _activeTab == i;
                        return GestureDetector(
                          onTap: () => setState(() => _activeTab = i),
                          child: Container(
                            margin: EdgeInsets.only(right: i < 3 ? 8 : 0),
                            padding: const EdgeInsets.symmetric(
                                horizontal: 14, vertical: 7),
                            decoration: BoxDecoration(
                              color: isActive
                                  ? AppColors.sage100
                                  : AppColors.card,
                              borderRadius: BorderRadius.circular(999),
                              border: Border.all(
                                color: isActive
                                    ? AppColors.sage300
                                    : AppColors.border,
                                width: 1.5,
                              ),
                            ),
                            child: Text(
                              t,
                              style: TextStyle(
                                fontSize: 11,
                                fontWeight: isActive
                                    ? FontWeight.w700
                                    : FontWeight.w500,
                                color: isActive
                                    ? AppColors.sage700
                                    : AppColors.neutral500,
                              ),
                            ),
                          ),
                        );
                      }).toList(),
                    ),
                  ),

                  const Divider(height: 1),
                ],
              ),
            ),
          ),

          // ── Scrollable content — switches based on _activeTab ───────────
          Expanded(
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 300),
              switchInCurve: Curves.easeOutCubic,
              switchOutCurve: Curves.easeInCubic,
              transitionBuilder: (child, anim) => FadeTransition(
                opacity: anim,
                child: SlideTransition(
                  position: Tween<Offset>(
                    begin: const Offset(0.04, 0),
                    end: Offset.zero,
                  ).animate(anim),
                  child: child,
                ),
              ),
              child: SingleChildScrollView(
                key: ValueKey(_activeTab),
                physics: const BouncingScrollPhysics(),
                padding: const EdgeInsets.all(16),
                child: Column(
                  children: [
                    ..._buildTabContent(sleep, water, meds),
                    const SizedBox(height: 12),
                    // Export / Share row
                    Row(
                      children: [
                        Expanded(
                          child: _ExportBtn(
                            label: '📄 PDF',
                            bg: AppColors.plum900,
                            fg: Colors.white,
                            onTap: _exportPdf,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: _ExportBtn(
                            label: '📊 CSV',
                            bg: AppColors.surface,
                            fg: AppColors.plum900,
                            border: AppColors.border,
                            onTap: _exportCsv,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: _ExportBtn(
                            label: '↗ Share',
                            bg: AppColors.sage600,
                            fg: Colors.white,
                            onTap: _shareReport,
                          ),
                        ),
                      ],
                    ).animate().fadeIn(delay: 220.ms, duration: 300.ms),
                    const SizedBox(height: 100),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  List<Widget> _buildTabContent(
      SleepState sleep, WaterState water, MedicationState meds) {
    switch (_activeTab) {
      case 0: // All
        return [
          _buildSleepCard(sleep),
          const SizedBox(height: 12),
          _buildWaterCard(water),
          const SizedBox(height: 12),
          _buildMedAdherenceCard(meds),
        ];
      case 1: // Sleep
        return [
          _buildSleepCard(sleep),
          const SizedBox(height: 12),
          _SleepStatsCard(sleep: sleep),
          const SizedBox(height: 12),
          _SleepHistoryCard(sleep: sleep),
        ];
      case 2: // Water
        return [
          _buildWaterCard(water),
          const SizedBox(height: 12),
          _WaterStatsCard(water: water),
        ];
      case 3: // Medications
        return [
          _buildMedAdherenceCard(meds),
          const SizedBox(height: 12),
          _MedListCard(meds: meds),
        ];
      default:
        return [];
    }
  }

  Widget _buildSleepCard(SleepState sleep) {
    final data = sleep.weeklyHours;
    if (data.isEmpty || data.every((h) => h == 0)) {
      return _EmptyDataCard(
        emoji: '🌙',
        title: 'Sleep Data',
        message: 'No sleep logs yet. Log your first sleep session!',
      );
    }
    return _SleepBarsCard(data: data, days: SleepState.weekLabels)
        .animate()
        .fadeIn(duration: 300.ms);
  }

  Widget _buildWaterCard(WaterState water) {
    // Build a 7-day mock using today's total (real history requires backend)
    if (water.totalMl == 0) {
      return _EmptyDataCard(
        emoji: '💧',
        title: 'Hydration Data',
        message: 'No water logged today. Start tracking your hydration!',
      );
    }
    return _WaterBarCard(todayMl: water.totalMl)
        .animate()
        .fadeIn(duration: 300.ms);
  }

  Widget _buildMedAdherenceCard(MedicationState meds) {
    if (meds.medications.isEmpty) {
      return _EmptyDataCard(
        emoji: '💊',
        title: 'Medication Data',
        message: 'No medications added yet.',
      );
    }
    final taken = meds.medications.where((m) => m.isTaken).length;
    final total = meds.medications.length;
    final pct = total > 0 ? taken / total : 0.0;
    return _AdherenceCard(taken: taken, total: total, pct: pct)
        .animate()
        .fadeIn(delay: 160.ms, duration: 300.ms);
  }
}

// ─── Empty Data Card ──────────────────────────────────────────────────────────

class _EmptyDataCard extends StatelessWidget {
  final String emoji;
  final String title;
  final String message;

  const _EmptyDataCard(
      {required this.emoji, required this.title, required this.message});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(24),
      child: Column(
        children: [
          Text(emoji, style: const TextStyle(fontSize: 36)),
          const SizedBox(height: 10),
          Text(title, style: AppTextStyles.cardTitle),
          const SizedBox(height: 6),
          Text(
            message,
            style: AppTextStyles.caption,
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

// ─── Sleep Bars Card ──────────────────────────────────────────────────────────

class _SleepBarsCard extends StatelessWidget {
  final List<double> data;
  final List<String> days;

  const _SleepBarsCard({required this.data, required this.days});

  @override
  Widget build(BuildContext context) {
    final maxH = data.isEmpty ? 1.0 : data.reduce(math.max).clamp(1.0, 24.0);
    final avg = data.isEmpty
        ? 0.0
        : data.reduce((a, b) => a + b) / data.length;

    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Sleep Pattern', style: AppTextStyles.cardTitle),
          const SizedBox(height: 2),
          Text(
            'Avg ${avg.toStringAsFixed(1)}h · Recommended: 8h',
            style: AppTextStyles.caption,
          ),
          const SizedBox(height: 14),
          SizedBox(
            height: 100,
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.end,
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: List.generate(data.length, (i) {
                final h = data[i];
                final barH = ((h / maxH) * 80).clamp(2.0, 80.0);
                final isToday = i == data.length - 1;
                final label = i < days.length ? days[i] : '';
                final isGood = h >= 7;

                return Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    if (h > 0)
                      Text(
                        '${h.toStringAsFixed(1)}',
                        style: TextStyle(
                          fontSize: 8,
                          fontWeight: FontWeight.w700,
                          color: isToday ? AppColors.plum900 : AppColors.neutral400,
                        ),
                      ),
                    const SizedBox(height: 2),
                    TweenAnimationBuilder<double>(
                      tween: Tween(begin: 0, end: barH),
                      duration: Duration(milliseconds: 400 + i * 50),
                      curve: Curves.easeOutCubic,
                      builder: (_, val, __) => Container(
                        width: 28,
                        height: val,
                        decoration: BoxDecoration(
                          color: isGood
                              ? (isToday ? AppColors.plum900 : AppColors.plum500)
                              : AppColors.rose400,
                          borderRadius: const BorderRadius.vertical(
                              top: Radius.circular(5)),
                        ),
                      ),
                    ),
                    const SizedBox(height: 5),
                    Text(
                      label,
                      style: TextStyle(
                        fontSize: 9,
                        fontWeight: isToday ? FontWeight.w700 : FontWeight.w500,
                        color: isToday
                            ? AppColors.plum900
                            : AppColors.neutral400,
                      ),
                    ),
                  ],
                );
              }),
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Sleep History Card ───────────────────────────────────────────────────────

class _SleepHistoryCard extends StatelessWidget {
  final SleepState sleep;
  const _SleepHistoryCard({required this.sleep});

  @override
  Widget build(BuildContext context) {
    final logs = sleep.historyLogs;
    if (logs.isEmpty) {
      return Container(
        decoration: cardDecoration(),
        padding: const EdgeInsets.all(18),
        child: Column(children: [
          const Text('📅', style: TextStyle(fontSize: 30)),
          const SizedBox(height: 8),
          Text('No sleep history yet', style: AppTextStyles.bodySemiBold),
          const SizedBox(height: 4),
          Text('Past sleep sessions will appear here',
              style: AppTextStyles.caption, textAlign: TextAlign.center),
        ]),
      );
    }

    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          const Text('📅', style: TextStyle(fontSize: 18)),
          const SizedBox(width: 8),
          Text('Sleep History', style: AppTextStyles.cardTitle),
          const Spacer(),
          Text('${logs.length} sessions', style: AppTextStyles.caption),
        ]),
        const SizedBox(height: 12),
        const Divider(height: 1),
        ...logs.take(14).map((log) {
          final startStr = log['sleep_start'] as String?;
          final hours = SleepState.safeDuration(log);
          final quality = (log['quality'] as num?)?.toInt() ?? 0;
          DateTime? start;
          try { if (startStr != null) start = DateTime.parse(startStr); } catch (_) {}
          final dateLabel = start != null
              ? DateFormat('EEE, MMM d').format(start) : '—';

          final Color barColor = hours >= 7
              ? AppColors.sage500
              : hours >= 5
                  ? const Color(0xFFF59E0B)
                  : AppColors.rose400;

          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 9),
            child: Row(children: [
              SizedBox(
                width: 88,
                child: Text(dateLabel,
                    style: AppTextStyles.caption.copyWith(
                        fontWeight: FontWeight.w600,
                        color: AppColors.textSecondary)),
              ),
              Expanded(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(999),
                  child: LinearProgressIndicator(
                    value: (hours / 9).clamp(0.0, 1.0),
                    backgroundColor: AppColors.border,
                    valueColor: AlwaysStoppedAnimation(barColor),
                    minHeight: 8,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text('${hours.toStringAsFixed(1)}h',
                  style: TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                      color: barColor)),
              const SizedBox(width: 6),
              Row(children: List.generate(5, (i) => Icon(
                i < quality ? Icons.star_rounded : Icons.star_outline_rounded,
                color: Colors.amber, size: 10))),
            ]),
          );
        }),
      ]),
    );
  }
}

// ─── Sleep Stats Card ────────────────────────────────────────────────────────

class _SleepStatsCard extends StatelessWidget {
  final SleepState sleep;
  const _SleepStatsCard({required this.sleep});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Sleep Summary', style: AppTextStyles.cardTitle),
          const SizedBox(height: 14),
          Row(
            children: [
              Expanded(
                child: _StatTile(
                  label: 'Last Night',
                  value: '${sleep.lastNightHours.toStringAsFixed(1)}h',
                  emoji: '🌙',
                  good: sleep.lastNightHours >= 7,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _StatTile(
                  label: 'Weekly Avg',
                  value: '${sleep.averageHours.toStringAsFixed(1)}h',
                  emoji: '📊',
                  good: sleep.averageHours >= 7,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _StatTile(
                  label: 'Quality',
                  value: '${sleep.lastNightQuality}/5',
                  emoji: '⭐',
                  good: sleep.lastNightQuality >= 3,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ─── Water Bar Card ───────────────────────────────────────────────────────────

class _WaterBarCard extends StatelessWidget {
  final int todayMl;
  const _WaterBarCard({required this.todayMl});

  @override
  Widget build(BuildContext context) {
    final goalMl = AppConstants.dailyWaterGoalMl;
    final pct = (todayMl / goalMl).clamp(0.0, 1.0);

    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Hydration Today', style: AppTextStyles.cardTitle),
          const SizedBox(height: 2),
          Text(
            '${(todayMl / 1000).toStringAsFixed(2)} L of ${(goalMl / 1000).toStringAsFixed(1)} L goal',
            style: AppTextStyles.caption,
          ),
          const SizedBox(height: 16),
          // Big gauge
          TweenAnimationBuilder<double>(
            tween: Tween(begin: 0, end: pct),
            duration: const Duration(milliseconds: 800),
            curve: Curves.easeOutCubic,
            builder: (_, val, __) => Column(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(999),
                  child: LinearProgressIndicator(
                    value: val,
                    minHeight: 18,
                    backgroundColor: AppColors.neutral100,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      pct >= 1.0
                          ? AppColors.sage600
                          : const Color(0xFF2196F3),
                    ),
                  ),
                ),
                const SizedBox(height: 8),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text('${todayMl} ml consumed',
                        style: AppTextStyles.caption),
                    Text('${(pct * 100).round()}%',
                        style: AppTextStyles.caption.copyWith(
                          fontWeight: FontWeight.w700,
                          color: AppColors.plum700,
                        )),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Water Stats Card ────────────────────────────────────────────────────────

class _WaterStatsCard extends StatelessWidget {
  final WaterState water;
  const _WaterStatsCard({required this.water});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Hydration Breakdown', style: AppTextStyles.cardTitle),
          const SizedBox(height: 14),
          Row(
            children: [
              Expanded(
                child: _StatTile(
                  label: 'Full Glasses',
                  value: '${water.fullGlasses}',
                  emoji: '🥛',
                  good: water.fullGlasses >= 6,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _StatTile(
                  label: 'Current',
                  value: '${water.currentGlassMl} ml',
                  emoji: '💧',
                  good: true,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _StatTile(
                  label: 'Remaining',
                  value:
                      '${((AppConstants.dailyWaterGoalMl - water.totalMl).clamp(0, 9999) / 1000).toStringAsFixed(2)} L',
                  emoji: '🎯',
                  good: water.totalMl >= AppConstants.dailyWaterGoalMl,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ─── Medication Adherence Card ────────────────────────────────────────────────

class _AdherenceCard extends StatelessWidget {
  final int taken;
  final int total;
  final double pct;

  const _AdherenceCard(
      {required this.taken, required this.total, required this.pct});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('Medication Adherence', style: AppTextStyles.cardTitle),
              Text('Today · $total medications', style: AppTextStyles.caption),
            ],
          ),
          const SizedBox(height: 14),
          SizedBox(
            width: 140,
            height: 80,
            child: CustomPaint(
              painter: _GaugePainter(pct: pct),
              child: Align(
                alignment: const Alignment(0, 0.4),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      '${(pct * 100).round()}%',
                      style: GoogleFonts.playfairDisplay(
                        fontSize: 22,
                        fontWeight: FontWeight.w700,
                        color: AppColors.plum900,
                      ),
                    ),
                    Text('on-time doses', style: AppTextStyles.caption),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(
                child: Container(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  decoration: BoxDecoration(
                    color: AppColors.sage100,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    '✓ $taken Taken',
                    style: const TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                      color: AppColors.sage700,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: Container(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  decoration: BoxDecoration(
                    color: AppColors.rose100,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    '✗ ${total - taken} Missed',
                    style: const TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.w700,
                      color: AppColors.rose700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ─── Med List Card ────────────────────────────────────────────────────────────

class _MedListCard extends StatelessWidget {
  final MedicationState meds;
  const _MedListCard({required this.meds});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: cardDecoration(),
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Medication List', style: AppTextStyles.cardTitle),
          const SizedBox(height: 12),
          ...meds.medications.take(5).map((m) => Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: Row(
                  children: [
                    Container(
                      width: 36,
                      height: 36,
                      decoration: BoxDecoration(
                        color: m.isTaken ? AppColors.sage100 : AppColors.rose50,
                        borderRadius: BorderRadius.circular(10),
                      ),
                      alignment: Alignment.center,
                      child: Text(m.isTaken ? '✓' : '!',
                          style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w800,
                            color: m.isTaken
                                ? AppColors.sage700
                                : AppColors.rose700,
                          )),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('${m.name} — ${m.dosage}',
                              style: AppTextStyles.bodySemiBold),
                          Text(m.frequencyLabel, style: AppTextStyles.caption),
                        ],
                      ),
                    ),
                    Text(
                      m.isTaken ? 'Taken' : 'Pending',
                      style: TextStyle(
                        fontSize: 11,
                        fontWeight: FontWeight.w700,
                        color: m.isTaken ? AppColors.sage600 : AppColors.rose500,
                      ),
                    ),
                  ],
                ),
              )),
        ],
      ),
    );
  }
}

// ─── Shared stat tile ────────────────────────────────────────────────────────

class _StatTile extends StatelessWidget {
  final String label;
  final String value;
  final String emoji;
  final bool good;

  const _StatTile(
      {required this.label,
      required this.value,
      required this.emoji,
      required this.good});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: good ? AppColors.sage50 : AppColors.rose50,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
            color: good ? AppColors.sage200 : AppColors.rose200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(emoji, style: const TextStyle(fontSize: 18)),
          const SizedBox(height: 4),
          Text(value,
              style: GoogleFonts.playfairDisplay(
                fontSize: 15,
                fontWeight: FontWeight.w700,
                color: AppColors.textPrimary,
              )),
          Text(label, style: AppTextStyles.caption),
        ],
      ),
    );
  }
}

class _GaugePainter extends CustomPainter {
  final double pct;
  const _GaugePainter({required this.pct});

  @override
  void paint(Canvas canvas, Size size) {
    final c = Offset(size.width / 2, size.height);
    const r = 60.0;
    const startAngle = math.pi;
    const sweepAngle = math.pi;

    canvas.drawArc(
      Rect.fromCircle(center: c, radius: r),
      startAngle,
      sweepAngle,
      false,
      Paint()
        ..color = AppColors.border
        ..style = PaintingStyle.stroke
        ..strokeWidth = 12
        ..strokeCap = StrokeCap.round,
    );
    canvas.drawArc(
      Rect.fromCircle(center: c, radius: r),
      startAngle,
      sweepAngle * pct.clamp(0, 1),
      false,
      Paint()
        ..color = AppColors.sage600
        ..style = PaintingStyle.stroke
        ..strokeWidth = 12
        ..strokeCap = StrokeCap.round,
    );
  }

  @override
  bool shouldRepaint(covariant _GaugePainter old) => old.pct != pct;
}

class _ExportBtn extends StatelessWidget {
  final String label;
  final Color bg;
  final Color fg;
  final Color? border;
  final VoidCallback onTap;

  const _ExportBtn(
      {required this.label,
      required this.bg,
      required this.fg,
      this.border,
      required this.onTap});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: bg,
          borderRadius: BorderRadius.circular(999),
          border: border != null ? Border.all(color: border!, width: 1.5) : null,
        ),
        alignment: Alignment.center,
        child: Text(label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w700,
              color: fg,
            )),
      ),
    );
  }
}
